### ISSUE TITLE
Fix Genome stats a bit so it's not total bogus

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dictyaccess#11]
On the Genome stats https://testdb.dictybase.org/dictyaccess/genomes

In principle I'd like to show this page but it's too much bogus. Can this be done a bit more real so headers fit what's in the box plus it make sense?

I like the mouse over of the columns that looks really neat that's why I'd like to show. But needs a bit more 'real' data and good titles
@wildlifehexagon let's maybe talk about it while we both look at it.

**Comment by wildlifehexagon** [comment]
Per earlier discussion, we are showing "coming soon" notices on these pages instead of fake content.
